baseURL = "https://nekkiichi.netlify.app/"
languageCode = "id"
DefaultContentLanguage = "id"
title = "Nekkichi website 🌵"
section="home"
description = "Nekkiichi blog website. owned by Agung Adhinata"
theme = "nohatt"
footnoteReturnLinkContents = "^"
summarylength = 30

pygmentsCodefences = true
pygmentsStyle = "pygments"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[minify]
  disableXML = true

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
  Description = "Homepage of nekkiichi blog website. owned by Agung Adhinata"
  taxonomiesExcludedFromSitemap = ["tags", "categories"]
  